version: '2'
services:
    blogs-service:
        build: .
        image: golang:1.10.4
        restart: always
        working_dir: /go/src
        command: ./blogs
        ports:
            - "8080:8080"
        volumes:
            - ./blogs-service/config/config.toml:/go/src/config.toml:ro
            - ./build/blogs:/go/src/blogs:ro
            - ./log:/go/src/log