version: '2'
services:
    blogs-service:
        build: .
        image: golang:1.10.4
        restart: always
        working_dir: /go/src
        command: ./blogs-service
        ports:
            - "8080:8080"
        volumes:
            - ./blogs-service/build/blogs-service:/go/src/blogs-service:ro
            - ./blogs-service/config/config.toml:/go/src/config.toml:ro
            - ./log:/go/src/log